# Generated by Django 4.1.4 on 2022-12-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=1000)),
                ('destination', models.CharField(max_length=1000)),
                ('pick_up_time', models.DateTimeField()),
                ('is_flexible_time', models.BooleanField(default=False)),
                ('travel_medium', models.CharField(choices=[('BUS', 'BUS'), ('CAR', 'CAR'), ('TRAIN', 'TRAIN')], max_length=1000)),
                ('asset_count', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='requester',
            name='to_deliver_phone_no',
            field=models.CharField(max_length=10),
        ),
    ]
