# Generated by Django 4.1.4 on 2022-12-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_api', '0002_rider_alter_requester_to_deliver_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='requester',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('EXPIRED', 'EXPIRED')], default='PENDING', max_length=1000),
        ),
    ]
