# Generated by Django 4.1.4 on 2022-12-25 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ride_api', '0004_remove_requester_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requester',
            name='rider_assigned',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ride_api.rider'),
        ),
    ]
