ASSET_CHOICES = (
    ('LAPTOP', 'LAPTOP'),
    ('TRAVEL_BAG', 'TRAVEL_BAG'),
    ('PACKAGE', 'PACKAGE'))

SENSITIVE_CHOICES = (
    ('HIGHLY_SENSITIVE', 'HIGHLY_SENSITIVE'),
    ('SENSITIVE', 'SENSITIVE'),
    ('NORMAL', 'NORMAL')
)

TRAVEL_MEDIUM_CHOICES = (
    ('BUS', 'BUS'),
    ('CAR', 'CAR'),
    ('TRAIN', 'TRAIN')
)

REQUEST_STATUS_CHOICES = {"PENDING", "EXPIRED"}
